-- AlterTable
ALTER TABLE "User" ADD COLUMN "isSuperhost" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Listing" ADD COLUMN "latitude" DOUBLE PRECISION,
ADD COLUMN "longitude" DOUBLE PRECISION,
ADD COLUMN "reviewCount" INTEGER NOT NULL DEFAULT 0;
